import { execSync } from "node:child_process";
import { Octokit } from "@octokit/rest";
import type { RunContext, WorkflowAnalysis, PatchResult } from "../shared/types.js";
import { loadPatches } from "../patches/index.js";
import { perceive } from "./perception.js";
import { perceiveLocal, writeLocal, resolveWorkspace } from "./local-runner.js";

/**
 * agent/index.ts — Decision engine
 *
 * Orchestrates the detect → apply → commit/comment pipeline:
 *
 *   1. Perceive  — load workflow files (API or disk)
 *   2. Detect    — ask each registered patch whether it applies
 *   3. Apply     — collect PatchResults from applicable patches
 *   4. Act       — commit fixes via API / git, or leave a PR comment
 */

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Post a PR comment listing all applied (or detected) patches. */
async function postComment(
  octokit: Octokit,
  owner: string,
  repo: string,
  prNumber: number,
  results: PatchResult[]
): Promise<void> {
  const lines = results.map(
    (r) =>
      `- **${r.patchId}**: ${r.summary}${r.commit ? " ✅ auto-committed" : " ⚠️ manual fix needed"}`
  );
  const body = [
    "## 🔧 Thresh — self-healing pipeline report",
    "",
    ...lines,
    "",
    "_Generated by [Thresh](https://github.com/QueenFi703/thresh-agent)_",
  ].join("\n");

  await octokit.issues.createComment({ owner, repo, issue_number: prNumber, body });
}

/** Commit a patched file via the GitHub Contents API. */
async function commitViaApi(
  octokit: Octokit,
  owner: string,
  repo: string,
  result: PatchResult,
  ref: string
): Promise<void> {
  await octokit.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: result.path,
    message: `fix(thresh): ${result.summary}`,
    content: Buffer.from(result.content).toString("base64"),
    sha: result.sha,
    branch: ref,
  });
}

/** Commit a patched file via git on disk (local / composite Action mode). */
function commitViaGit(workspace: string, result: PatchResult): void {
  writeLocal(workspace, result.path, result.content);
  execSync(`git -C "${workspace}" add "${result.path}"`, { stdio: "inherit" });
  execSync(
    `git -C "${workspace}" commit -m "fix(thresh): ${result.summary}" --no-verify`,
    { stdio: "inherit" }
  );
}

// ─── Core run function ────────────────────────────────────────────────────────

export interface AgentRunOptions {
  ctx: RunContext;
  owner: string;
  repo: string;
  /** Git ref / branch name — used for API commits and perception. */
  ref?: string;
}

/**
 * Entry point for both server (webhook) and local (composite Action) modes.
 *
 * Returns the list of PatchResults that were detected (regardless of whether
 * `commit` was set), so callers can log or surface them.
 */
export async function run(options: AgentRunOptions): Promise<PatchResult[]> {
  const { ctx, owner, repo, ref } = options;
  const octokit = new Octokit({ auth: ctx.token });

  // ── 1. Perceive ─────────────────────────────────────────────────────────────
  let analysis: WorkflowAnalysis;
  if (ctx.workspace) {
    // Local / composite Action mode — read from disk.
    analysis = perceiveLocal(owner, repo, ctx.workspace);
  } else {
    // Server / webhook mode — read via GitHub API.
    analysis = await perceive(ctx.token, owner, repo, ref);
  }

  if (analysis.workflows.length === 0) {
    console.log("[thresh] No workflow files found — nothing to do.");
    return [];
  }

  // ── 2. Detect + Apply ───────────────────────────────────────────────────────
  const patches = await loadPatches();
  const results: PatchResult[] = [];

  for (const patch of patches) {
    if (!patch.detect(analysis)) continue;

    console.log(`[thresh] Patch applicable: ${patch.id}`);

    // Apply the patch and refresh the analysis so subsequent patches see the
    // updated raw content (important when multiple patches target the same file).
    const result = patch.apply(ctx, analysis);
    results.push(result);

    // Update the in-memory analysis so later patches see the patched content.
    analysis = {
      ...analysis,
      workflows: analysis.workflows.map((wf) =>
        wf.path === result.path
          ? { ...wf, raw: result.content, sha: result.sha }
          : wf
      ),
    };

    // ── 3. Commit or skip ─────────────────────────────────────────────────────
    if (!ctx.commitFixes || !result.commit) {
      console.log(`[thresh] Skipping commit for ${result.path} (commit-fixes=false)`);
      continue;
    }

    if (ctx.workspace) {
      // Local mode — git commit on disk.
      const ws = resolveWorkspace(ctx.workspace);
      commitViaGit(ws, result);
      console.log(`[thresh] Committed via git: ${result.path}`);
    } else if (ref) {
      // Server mode — commit via GitHub Contents API.
      await commitViaApi(octokit, owner, repo, result, ref);
      console.log(`[thresh] Committed via API: ${result.path}`);
    }
  }

  // ── 4. Comment on PR (if applicable) ────────────────────────────────────────
  if (results.length > 0 && ctx.prNumber) {
    await postComment(octokit, owner, repo, ctx.prNumber, results);
  }

  if (results.length === 0) {
    console.log("[thresh] No applicable patches — workflows look healthy.");
  } else {
    console.log(`[thresh] Applied ${results.length} patch(es).`);
  }

  return results;
}
